### PR TITLE
(keepass-plugin-otpkeyprov) Now maintained by tunisiano

### PR DESCRIPTION
**Pull request by tunisiano187**
Solving issue #400

---
This change is [Reviewable](https://reviewable.io/reviews/dtgm/chocolatey-packages/554)

### CODE REVIEW

**Review by gep13 — CHANGES_REQUESTED** [review]
Can you please update this PR to _not_ remove the icon file for the package.  These are left in this repository so that old package versions continue to have a working icon.

**Comment by tunisiano187** [comment]
@gep13, that's changed

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@tunisiano187 thanks!

**Pull request merged**
