### PR TITLE
Adding new keepass plugin KeeTrayTOTP

### PR DESCRIPTION
**Pull request by ebekker**
This plugin is effectively a continuation of and replacement for the original TrayTOTP plugin.

Adding as a _manual_ package which was adapted from the _automatic_ variation of TrayTOTP.
Original plugin TrayTOTP is no longer compatible with KeePass since 2.42 because of menu changes, but KeeTrayTOTP has been updated to work with versions before and after 2.42.  It also features a number of enhancements like better UI and better support for high DPI screens, and several new features.

### CODE REVIEW

**Comment by gep13** [comment]
@ebekker thank you for taking the time to create this PR.  Unfortunately, this repository is no longer being maintained, as it is known that @dtgm is no longer in a position to do so.  A process, albeit slowly, is being followed to remove packages from this repository and to hand them over to other maintainers.  I am hesitant to bring in any new packages to this repository as they will also not be correctly maintained.  I would suggest, if you are willing, that you start your own repository, where you can maintain this package.

Let me know what you think.

**Comment by ebekker** [comment]
@gep13, I would consider it since it is a tool I use myself.  However,  wanted to see if the main KeePass app and/or any of the other plugins for it have already been handed over to other maintainer(s)?  If so, would seem reasonable and perhaps preferred to keep them all together, and I can just try to contribute there?

**Comment by gep13** [comment]
@ebekker if the packages that you are interested in are still present in this repository, then the likelihood is that they haven't yet been handed over to another maintainer.  However, there are times when packages have been handed over and have not been removed from this repository.  Exactly which packages are you interested in?

**Comment by ebekker** [comment]
For my specific use, there's the main [KeePass](https://chocolatey.org/packages/keepass) app package, and the [KeePass KeeAnywhere](https://chocolatey.org/packages/keepass-plugin-keeanywhere) plugin, besides this KeyTrayTOTP plugin.

Now, taking a look at the package source links from those respective packages on choco, it looks like those may have already been relocated, as they point back to different GitHub sites, but not the same one.

**Comment by gep13** [comment]
@ebekker so, looks like @pauby is now looking after the main KeePass package, so perhaps a conversation with him might be good, to get any plugins related to it moved over to his repository?

**Comment by ebekker** [comment]
Thanks, will do!

**Pull request closed without merging**
