### PR TITLE
(ntfsinfo) now maintained by Tunisiano187

### PR DESCRIPTION
**Pull request by tunisiano187**

### CODE REVIEW

**Comment by tunisiano187** [comment]
Requested here : https://github.com/chocolatey-community/chocolatey-package-requests/issues/1250

**Comment by gep13** [comment]
@tunisiano187 did you see the comment from @TheCakeIsNaOH on your package review?

> You also may want to push this as 1.20.0.x so as to have a higher version than the previous latest of 1.20

The new package version that you have pushed isn't higher then the existing highest package version, so folks won't see if when installing.

Thanks for your help with this package!

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@tunisiano187 there was an extra `.dtcache` file in this PR, but I have taken it out.

**Pull request merged**
