### PR TITLE
Closes

### PR DESCRIPTION
**Pull request by basictheprogram**
https://github.com/chocolatey-community/chocolatey-package-requests/issues/614

Closes https://github.com/dtgm/chocolatey-packages/issues/452

Please remove scilab the list of maintained packages. A RFM was opened
<https://github.com/chocolatey-community/chocolatey-package-requests/issues/614>
and I have volunteered to take over the management of the scilab package
<https://github.com/basictheprogram/chocolatey-scilab>

### CODE REVIEW

**Comment by gep13** [comment]
@basictheprogram thank you for taking the time to do this.  Can you please update the PR to "not" remove the files in the output folder?  These are typically left in tact in the repository.

**Comment by gep13** [comment]
@basictheprogram not sure what happened here, but looks like there are now no longer any files changed as part of this PR.  Can you please confirm?

**Comment by basictheprogram** [comment]
You [said](https://github.com/dtgm/chocolatey-packages/pull/463#issuecomment-554977269) "... update the PR to "not" remove the files in the output folder ..." 

So I did that. 

I put all the files in the output folder back and committed.

**Comment by gep13** [comment]
@basictheprogram I am not exactly sure what has happened in this PR, but currently there are no changes currently to be applied to the repository:

image

As a result, this PR doesn't do anything.

**Comment by gep13** [comment]
I have deleted the required files from this repository, so I am going to go ahead and close this PR.

**Pull request closed without merging**
