### PR TITLE
(Install4J) now maintained by tunisiano

### PR DESCRIPTION
**Pull request by tunisiano187**
Hello,
I've missed the portable one, i'll prepare it and ask for it too.

### CODE REVIEW

**Comment by tunisiano187** [comment]
Added

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@tunisiano187 this PR looks good, but I noticed that you haven't pushed the updated metapackage `install4j`.  Is that something that you are still planning on doing?

**Comment by tunisiano187** [comment]
It's indeed what it should do, but, it was stuck...
i've tryied something else

**Comment by tunisiano187** [comment]
This correction worked, it's been pushed

**Comment by gep13** [comment]
@tunisiano187 thanks for checking!

Happy to approve the package, as it is just a refresh of the existing package scripts, however, for future versions, you might want to think about removing the `chocolateyUninstall.ps1` from the meta package, as this should no longer be required, as Chocolatey CLI will take care of that.

**Comment by gep13** [comment]
@tunisiano187 thanks again for your help with this package, and all the other packages that you are working on!

**Pull request merged**
