### PR TITLE
googlecode.com -> storage.googleapis.com

### PR DESCRIPTION
**Pull request by galeksandrp**

### CODE REVIEW

**Comment by dtgm** [comment]
Thanks for bringing this to my attention! 

However, I don't accept PRs that change files in _output/*. Those files are just for reference. Can you remove those file changes from this PR and instead change the source files that the packages are built from? For example, instead of
`automatic/_output/aaclr/1.0.2/tools/chocolateyInstall.ps1
`
the correct file is
`automatic/aaclr/tools/chocolateyInstall.ps1
`

Thank you!

**Comment by galeksandrp** [comment]
Affected version of packages with links fixed created in `manual/`.

**Comment by gep13** [comment]
@galeksandrp I am trying to help @dtgm with some of these open PR's...

Can you please help me understand what this change was trying to do?  Why have all these new files been created?

**Comment by galeksandrp** [comment]
I am migrated urls in some manual packages due to Google Code shutdown, but for now this PR is not needed since all affected packages are now build automatically.

**Pull request closed without merging**
