### PR TITLE
Update chocolateyUninstall.ps1

### PR DESCRIPTION
**Pull request by RedBaron2**
Spybot 2 changed the location in the registry to be a Hive name; This will find the correct hive name, and choose the correct uninstall file with Silent Argument.
Should work except for the extremely rare chance they have a 32bit install on a 64bit system under hkcu

### CODE REVIEW

**Comment by RedBaron2** [comment]
Updated the uninstall to now work for the extremely rare chance they have a 32bit install on a 64bit system under hkcu

**Comment by RedBaron2** [comment]
@dtgm 
I just updated this to use a chocolatey helper. A small if check to see if the variable is null and uses the non silent method. Though this should almost never happen with spybot 2. The problem does arise that the uninstaller is not silent do to safer networking not using their own silent switch.

**Comment by RedBaron2** [comment]
@dtgm
I know that you have been having limited time for Chocolatey projects. If you are able to merge this PR it would be extremely helpful.

**Comment by gep13** [comment]
@RedBaron2 I just wanted to check...

This seems to be editing the generated output file.  Are you expecting a new package version with the fix notation to be generated?

Should this not also be done on the source uninstall file as well?

**Comment by RedBaron2** [comment]
@gep13 @dtgm 
Fixed the edit to be the right file.
This should be correct now

**Comment by gep13** [comment]
@RedBaron2 thank you for making this change!

**Pull request merged**
