### PR TITLE
multimonitortool - Migrate package maintenance

### PR DESCRIPTION
**Pull request by brogers5**
Per https://github.com/chocolatey-community/chocolatey-package-requests/issues/1195, I've picked up maintenance of this package.

Removing from this repository, as the package is now being maintained at [brogers5/chocolatey-package-multimonitortool](https://github.com/brogers5/chocolatey-package-multimonitortool).

### CODE REVIEW

**Comment by gep13** [comment]
@brogers5 thank you for taking the time to raise this PR and for maintaining this package!

Can you update this PR to not include the deletion of the .png file? We leave it in place in this repository so that older package versions still have a valid iconUrl.

Thanks!

**Comment by brogers5** [comment]
@gep13, the legacy `iconUrl` (for reference, https://cdn.rawgit.com/dtgm/chocolatey-packages/2697586f564894b3346352497da46f320a02e725/icons/multimonitortool.png) is referring to the file's state as of a specific commit hash.

My understanding is that so long as the original commit remains as-is in this repository, the legacy `iconUrl` should remain valid, regardless of the file's current state in `master`. Based on a quick search, I'm finding this is true even for deleted files.

Example legacy icon URL for Telegram: https://cdn.rawgit.com/dtgm/chocolatey-packages/22f97d7004cdb3702d7ac64d4fc81b47e25e89cf/icons/telegram.png
This file was removed in 9b7b192a8aaec825b7b2a138d2b789c2660918c7.

Is there something I'm missing?

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@brogers5 the concern here was that the same hashed iconUrl hadn't been used in every single package version that exists on the Chocolatey Community Repository.  To prevent the need to go through each package version, it is simply easier to leave the icon in place in this repository, since it doesn't do any harm.

However, in this case, it looks like the hashed URL was in place from the first package version, so removing the file from the repository makes sense in this case.

**Comment by gep13** [comment]
@brogers5 thank you for removing these files, and for helping with the maintenance of this package.

**Pull request merged**
