### PR TITLE
(Jacksum) now maintained by tunisiano

### PR DESCRIPTION
**Pull request by tunisiano187**

### CODE REVIEW

**Comment by gep13** [comment]
@tunisiano187 are you in the process of pushing a new package version for this one?  I don't see you as a maintainer on this package yet.

**Comment by tunisiano187** [comment]
Hi, i've requested, to be added, i'm waiting for it.
Same for freepascal.

**Comment by gep13** [comment]
@tunisiano187 is there a reason that you closed this PR? It looks like you are now the owner of this package, and it would make sense to remove the files from this repository.

**Comment by tunisiano187** [comment]
No, mistake, I'll reopen it asap

**Pull request closed without merging**
