### PR TITLE
@added: New version of QuiteRSS 0.18.6

### PR DESCRIPTION
**Pull request by K0FF**
I'm added a new version of QuiteRSS 0.18.6

### CODE REVIEW

**Comment by k0ff** [comment]
Sorry, I'm newbie in Chocolate and forgotten add QuiteRSS version to quiterss.nuspec file

**Comment by gep13** [comment]
@k0ff in order to modify the packages within this repository, changes are made to the source files in the automatic folder, rather than in the _output folder.  Are you in a position to modify the required files in this location, rather than what you have done here?  Thanks

**Comment by majkinetor** [comment]
This is already moved to core team repo and up to date

**Comment by gep13** [comment]
@majkinetor was there a PR to remove it from this repo?

**Comment by gep13** [comment]
Ah, there was:

https://github.com/dtgm/chocolatey-packages/pull/336

Thanks for the nudge.

**Pull request closed without merging**
