### PR TITLE
Updated rufus.install

### PR DESCRIPTION
**Pull request by xmha97**

### CODE REVIEW

**Comment by tunisiano187** [comment]
Hello @xmha97,
if you're OK with it, i'll take the package and automate the update of it

**Comment by xmha97** [comment]
OK, Thanks.

**Comment by gep13** [comment]
@xmha97 @tunisiano187 can either of you confirm what should happen with this PR?  Should we close it out?

**Comment by tunisiano187** [comment]
@gep13 if it can be pushed quickly, you can merge it, i'm still working on the automation.

**Comment by gep13** [comment]
@tunisiano187 I would suggest that it would be better to use your new package version with AU automation.  So if you can let me know when that is ready, we can get this closed out, and then get another PR to review the files from this repository.

**Comment by tunisiano187** [comment]
Sorry, I forgot to send you the info, it's on it's way on my git, so this can be closed

**Comment by gep13** [comment]
@tunisiano187 sounds good.

**Comment by gep13** [comment]
@xmha97 thanks for taking the time to raise this PR, however, we have been moving these packages out of this repository into other AU repositories like @tunisiano187 so it is better to do this than to update packages directly here.

**Pull request closed without merging**
