### PR TITLE
monero now maintained by tunisiano on https://gitlab.com/chocolatey-p…

### PR DESCRIPTION
**Pull request by tunisiano187**
monero now maintained by tunisiano on https://gitlab.com/chocolatey-packages/automatic-updating/-/tree/master/automatic/monero

### CODE REVIEW

**Comment by gep13** [comment]
@tunisiano187 quick question....

I see the monero package in your repository, but I don't see the scite package.  Can you confirm where that is being maintained?  Thanks

**Comment by tunisiano187** [comment]
Oups, the squite is in triage, sorry for this one i've been too quick.
I've asked the maintainers today, so i'll wait a week for it.

**Comment by tunisiano187** [comment]
It's already ready in my test environment, if they give me the role, i can send it quickly

**Comment by gep13** [comment]
@tunisiano187 if you wanted to update this PR to only include the monero file deletions, I can go ahead and get this merged.

**Comment by gep13** [comment]
@tunisiano187 in fact, looks like dtgm was the last person to push versions of this package, and he is known to no longer be active, as you know, so I have added you as a maintainer of this package. Once you have all the pieces in place to push a new version of this package, let me know, and I will merge this PR.

**Comment by tunisiano187** [comment]
OK, that's in the Automatic folder and pushed to the community feed.
Thank you

**Comment by gep13** [comment]
@tunisiano187 thanks for getting that done!  Appreciate it!

**Pull request merged**
