### PR TITLE
Open ra maintained by others

### PR DESCRIPTION
**Pull request by tunisiano187**

### CODE REVIEW

**Comment by gep13** [comment]
@tunisiano187 am I right in saying that this PR can be closed?  I believe that all of these packaging files have already been removed.

**Comment by tunisiano187** [comment]
@gep13 OpenRA still needs to be closed

**Comment by gep13** [comment]
@tunisiano187 ok, let me attempt to rebase this PR onto the head of the current master branch, to see if that sorts things out.

**Comment by gep13** [comment]
@tunisiano187 I have rebased and merged this PR here:

https://github.com/dtgm/chocolatey-packages/commit/c7153522c8da79bfd5c536fddb8f12baa927d1c5

As a result, I am going to close out this PR, since it is no longer required.  Thanks!

**Pull request closed without merging**
