### PR TITLE
remove tortoisehg for new maintainer

### LINKED ISSUE #391: Tortoise Hg: Update to version 4.6
Latest version number: 4.6
Release date: 2018-05-21
URL to the install binary:

    32-bit: https://bitbucket.org/tortoisehg/files/downloads/tortoisehg-4.6.0-x86.msi
    64-bit: https://bitbucket.org/tortoisehg/files/downloads/tortoisehg-4.6.0-x64.msi

Release notes: https://bitbucket.org/tortoisehg/thg/wiki/ReleaseNotes#!tortoisehg-46

### PR DESCRIPTION
**Pull request by Thieum**
Hi,
I'd like to take over the tortoisehg package as it doesn't work anymore in an automatic way (the x86 build is broken since a few releases, and prevent the package from being created from the original source - see https://bitbucket.org/tortoisehg/thg/issues/5170/tortoisehg-47-windows-32bit-not-available ).
I created a x64 only package here: https://github.com/Thieum/ChocolateyPackages/tree/master/tortoisehg

fix #391

### CODE REVIEW

**Comment by gep13** [comment]
@Thieum have you requested to be added as a maintainer of this package on chocolatey.org:

https://chocolatey.org/packages/tortoisehg

Once you have that, and have pushed your first updated version, we can come back to here to merge this PR.

**Comment by Thieum** [comment]
The contact site admin doesn't seem to work for this package at least. I'll try again later on a different network.

**Comment by gep13** [comment]
@Thieum that is a little strange.  Are you getting an error, if so, can you share it?

We recently made some changes to the site, but this was tested and has been shown to be working.

**Comment by gep13** [comment]
@Thieum hmm, not sure what is going on there.

Let's cut to the chase though...

What is your username on chocolatey.org, and I can get you added as a package maintainer.

**Comment by Thieum** [comment]
@gep13 it's Thieum22 : https://chocolatey.org/profiles/Thieum22

**Comment by gep13** [comment]
@Thieum done.  Let me know when you have pushed a new version, and we can get this PR closed.

**Comment by gep13** [comment]
@Thieum looks like you haven't accepted the request to become a maintainer:

image

You should have received an email asking you to accept.

**Comment by Thieum** [comment]
@gep13 nope, no email so far. Authentication is still broken for me as well on the website. It only work in private sessions. The moment cache is involved, I cannot login, but I guess it's a separate issue.

**Comment by gep13** [comment]
@Thieum can you try pushing the new package version again please?

**Comment by Thieum** [comment]
@gep13 it worked: https://chocolatey.org/packages/tortoisehg/4.8.2 Thanks!

**Comment by gep13** [comment]
@Thieum your changes have been merged, thanks for your contribution 👍

**Pull request merged**
