### PR TITLE
(openhardwaremonitor) Add Start Menu shortcut

### PR DESCRIPTION
**Pull request by tylerszabo**
Based on feedback from comments here: https://chocolatey.org/packages/openhardwaremonitor#comment-3593878039

### CODE REVIEW

**Comment by franklinyu** [comment]
How about `ilspy`: https://chocolatey.org/packages/ilspy#comment-1117136275

**Comment by dmp1ce** [comment]
Yes please.

**Comment by tylerszabo** [comment]
Do you mean to use this technique for `ilspy`? If so this technique should work fine for that. It's probably best to create a separate PR.

If you're suggesting to use [`Install-ChocolateyDesktopLink`](https://chocolatey.org/docs/helpers-install-chocolatey-shortcut) it's deprecated in favor of [`Install-ChocolateyShortcut`](https://chocolatey.org/docs/helpers-install-chocolatey-shortcut) so I'd suggest sticking with `Install-ChocolateyShortcut` in some form.

**Comment by franklinyu** [comment]
All right, I can do it in separate pull request. Nevertheless I would like to wait until this is merged.

@gep13 Comments?

**Comment by gep13** [comment]
I have no objections to this getting added.

**Pull request merged**
