### PR TITLE
Package history and source migrated for maintenance transfer - dgalbraith

### PR DESCRIPTION
**Pull request by dgalbraith**
Package history and sources for the following:

* bluej
* bluej-bundled
* countrytraceroute
* fbcacheview
* gdiview
* ipnetinfo
* lsasecretsview
* mc
* monitorinfoview
* shellbagsview

have been migrated to [dgalbraith/chocolatey-packages](https://github.com/dgalbraith/chocolatey-packages) for ongoing maintenance.

### CODE REVIEW

**Review by gep13 — CHANGES_REQUESTED** [review]
Thanks for taking over all these packages, really appreciate it!

Just one thing though...  Can I ask that you update this PR to not remove the icon files from this repository?  Doing this would mean that the icons in older package versions on chocolatey.org will no longer work.  As such, we leave the icons in place in this repository so that things keeps working.

Thanks

**Comment by dgalbraith** [comment]
Certainly although there are 2 options here as I have already pushed/committed the deletes:
1. I re-clone the repository and reconstruct the commits/pull request sans the icon deletions; or
2. I revert the commits and re-add the icons to the existing pull request

Happy with either approach (2 is ready to go now, 1 would not take particularly long).  The advantage of the first option is that the integrity of the history would be maintained directly.

Any preferences on approach?

**Comment by gep13** [comment]
@dgalbraith either approach is fine with me, whichever is easiest.

As a side comment, creating a PR using the original master branch as the source branch isn't ideal.  It limits the amount of refactoring that can be done.  For future PR's, can you first create a branch from the master branch, and make the changes there, and then submit a PR using that branch?

**Comment by dgalbraith** [comment]
Point taken re branching.  It was just a small change.....

Anyway I have opted for a 3rd approach - git filter-repo for a bit of repository surgery to recover here.  The icons + associated history have been re-merged from dtgm/chocolatey-packages and are now available in the pull request.

This means the pull request will also show the historic commits by dtgm as well as my own - hopefully this is all ok but let me know if not and I can address in a different way.

**Comment by gep13** [comment]
@dgalbraith I think we can live with this.  Thanks for getting this updated!

**Review by gep13 — APPROVED** [review]
LGTM!

**Pull request merged**
