### PR TITLE
(disk2vhd) Remove this package

### PR DESCRIPTION
**Pull request by JPRuskin**
This package has become outdated, and needed updating. I've taken that up, and this commit removes it from this repository.

It's new location is 'https://github.com/JPRuskin/ChocolateyPackages/tree/main/packages/disk2vhd/'.

The icon has been left in place for displaying on existing package pages, though to my understanding they won't install correctly.

### CODE REVIEW

**Comment by gep13** [comment]
@JPRuskin if you can ping me a notification here once the nee package version is approved, I can get this PR merged.

**Comment by JPRuskin** [comment]
This is now good to go, @gep13!

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@JPRuskin thanks for your help with this package!

**Pull request merged**
