### PR TITLE
(Mweather) now maintained by tunisiano

### PR DESCRIPTION
**Pull request by tunisiano187**

### CODE REVIEW

**Comment by gep13** [comment]
Going to hold off on merging this one, as I see that you have pushed `mweather.install` but not the corresponding `mweather` package.  Are you planing on pushing/updating the meta package as well?

**Comment by tunisiano187** [comment]
Yes, it's waiting for the install to be accepted, to avoid having an error on the validation

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@tunisiano187 thank you for your help with this package!

**Pull request merged**
